[package]
name = "task_list_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
crossterm = "0.28.1"  # VersÃ£o estÃ¡vel do crossterm
tui = { version = "0.19.0", features = ["crossterm"] }
rand = "0.8"
